### ISSUE TITLE
System requirements are too high

### ISSUE THREAD

**Issue by knupero** [TeXhackse/LaTeX-ZUGFeRD#29]
Version v.08, dated 2024-09-11, works in principle here but has some issues.

Meanwhile, this package has become very demanding... a current TeX Live 2024 on openSUSE Tumbleweed is not sufficient to use the current version. Even the test with \IfPackageAtLeastF in zugferd.sty fails because this macro is not defined anywhere in TeX Live 2024. Is there a valid reason for this restriction of general usability?

**Comment by TeXhackse** [comment]
`\IfPackageAtLeast` was introduced in 2020… so it should exist.  But I will have a look. 

In general you need the pdfmanagement newer than 2024-09 because before that we had to abuse an internal interface. There are options to have a workaround on that … but I don't want to have that published inside the package as this would require to maintain all the backwards compatibility all the way. + Using the internal interface is not really a cool thing, see  #7

**Comment by t-b** [comment]
I've updated TL 2024 using `tlmgr update --all` and could then use the zugferd package.

**Comment by knupero** [comment]
tlmgr isn't provided by openSuSE. I installed a fresh tree from ctan.
