### ISSUE TITLE
Duplicate attachment entry in PDF

### ISSUE THREAD

**Issue by t-b** [TeXhackse/LaTeX-ZUGFeRD#32]
When I look at the test PDF files from this repo, i.e. build/test-config-pdf/minimal-pdf-15.pdf after running `l3build check` I see in okular and evince that xrechnung.xml is attached twice.

While mustang considers the file as valid, I don't think this needs to be duplicated.

Or is that due to the latex reruns which the documentation talks about? I've tried to only write/attach the xml file once via

```latex
\ExplSyntaxOn

\int_new:N \g_zugferd_invoice_written_int

\int_compare:nTF {\g_zugferd_invoice_written_int == 0} {
  \zugferd_enable_XML_interfaces:
  }{
  \int_set:Nn \g_zugferd_invoice_written_int {1}
  \zugferd_disable_XML_interfaces:
}

\ExplSyntaxOff
```

but that did not help. Sorry I'm a total expl3 noob.

**Comment by TeXhackse** [comment]
The attachment is not really there twice, There are two catalog entries. I will have a more detailed look. But atm I don't really thing it's an issue. I added the second one as described in #26 so that software is recognizing it as the correct file. It's valid. and the attachment you see as two attachments is the same one. 

Anyway it has nothing to do with the code running multiple times and even if your knipped would not change anything about because your test always reveals true. Additionally the XML interfaces only enable the interfaces. The command doing the writing is the ZUGFeRD environment as describd in the documentation.

**Comment by t-b** [comment]
> The attachment is not really there twice, There are two catalog entries. I will have a more detailed look. But atm I don't really thing it's an issue. I added the second one as described in https://github.com/TeXhackse/LaTeX-ZUGFeRD/issues/26 so that software is recognizing it as the correct file. It's valid. and the attachment you see as two attachments is the same one.

Good, thanks. This explains why the valdiator did not barf.

**Comment by t-b** [comment]
Verified the bug is fixed.
